JNU-econovation/jnu-wiki-be

src/main/java/com/timcooki/jnuwiki/domain/docs/entity/Docs.java
src/main/java/com/timcooki/jnuwiki/domain/docsArchive/entity/DocsArchive.java
src/main/java/com/timcooki/jnuwiki/domain/docsRequest/entity/DocsCategory.java
src/main/java/com/timcooki/jnuwiki/domain/docsRequest/entity/DocsRequest.java
src/main/java/com/timcooki/jnuwiki/domain/docsRequest/entity/DocsRequestType.java
src/main/java/com/timcooki/jnuwiki/domain/member/entity/Member.java
src/main/java/com/timcooki/jnuwiki/domain/member/entity/MemberRole.java

- create entity
- docs entity
- docsArchive entity
- docsRequest entity
- member entity
- x
- @pyg410 @jminkkk

feat: create entity

---

src/main/java/com/timcooki/jnuwiki/util/ApiError.java
src/main/java/com/timcooki/jnuwiki/util/ApiResult.java
src/main/java/com/timcooki/jnuwiki/util/ApiUtils.java

- ApiError.java
- ApiResult.java
- ApiUtils.java

API공통 포맷 구현

---

src/main/java/com/timcooki/jnuwiki/domain/docsRequest/service/DocsRequestService.java
src/main/java/com/timcooki/jnuwiki/domain/member/service/AdminService.java

사용안하는 import 제거

---

build.gradle
src/main/java/com/timcooki/jnuwiki/domain/docsRequest/controller/DocsRequestController.java
src/main/java/com/timcooki/jnuwiki/domain/docsRequest/service/DocsRequestService.java

mapstruct 설정 추가

---

src/main/java/com/timcooki/jnuwiki/domain/docs/DTO/response/ContentEditResDTO.java
src/main/java/com/timcooki/jnuwiki/domain/docs/DTO/response/ListReadResDTO.java
src/main/java/com/timcooki/jnuwiki/domain/docs/DTO/response/ReadResDTO.java
src/main/java/com/timcooki/jnuwiki/domain/docs/controller/DocsController.java
src/main/java/com/timcooki/jnuwiki/domain/docs/entity/Docs.java
src/main/java/com/timcooki/jnuwiki/domain/docs/repository/DocsRepository.java
src/main/java/com/timcooki/jnuwiki/domain/docs/service/DocsService.java
src/main/java/com/timcooki/jnuwiki/domain/member/DTO/response/admin/EditReadResDTO.java
src/main/java/com/timcooki/jnuwiki/domain/member/DTO/response/admin/NewReadResDTO.java

+ 문서 목록 조회 기능 구현 
+ 문서 상세 내역 조회 기능 구현
+ 문서 내용 수정 기능 구현
+ 생성, 수정 시간 타입 LocalDateTime으로 통일

문서 조회 및 내용 수정 기능 구현

---

src/main/java/com/timcooki/jnuwiki/domain/member/DTO/request/EditReqDTO.java
src/main/java/com/timcooki/jnuwiki/domain/member/DTO/response/ReadResDTO.java
src/main/java/com/timcooki/jnuwiki/domain/member/controller/MemberController.java
src/main/java/com/timcooki/jnuwiki/domain/member/entity/Member.java
src/main/java/com/timcooki/jnuwiki/domain/member/service/MemberService.java

- 사용자 조회
- 사용자 정보 수정
- Member Entity update() method 추가

사용자 조회, 사용자 정보 수정

---

src/main/java/com/timcooki/jnuwiki/domain/docs/DTO/response/SearchReadResDTO.java
src/main/java/com/timcooki/jnuwiki/domain/docs/controller/DocsController.java
src/main/java/com/timcooki/jnuwiki/domain/docs/entity/Docs.java
src/main/java/com/timcooki/jnuwiki/domain/docs/entity/DocsLocation.java
src/main/java/com/timcooki/jnuwiki/domain/docs/mapper/DocsMapper.java
src/main/java/com/timcooki/jnuwiki/domain/docs/repository/DocsRepository.java
src/main/java/com/timcooki/jnuwiki/domain/docs/service/DocsService.java
src/test/java/com/timcooki/jnuwiki/docs/DocsRepositoryTest.java

- 일반 검색 기능 구현
- 검색 테스트 구현
- DocsLocation,Docs OneToOne 매핑
- DocsMapper Impl
- SearchReadResDTO Impl

일반 검색 기능 구현, DocsLocation 테이블

---

src/main/java/com/timcooki/jnuwiki/domain/docs/entity/Docs.java
src/main/java/com/timcooki/jnuwiki/domain/docs/entity/DocsLocation.java
src/main/java/com/timcooki/jnuwiki/domain/docsRequest/controller/DocsRequestController.java
src/main/java/com/timcooki/jnuwiki/domain/docsRequest/entity/DocsRequest.java
src/main/java/com/timcooki/jnuwiki/domain/member/service/AdminService.java

+ 문서 위치 엔티티에서 @Embedded 사용으로 변경
+ 문서 요청 DTO와 엔티티간의 필드 매핑을 위해  이름 수정
+ 문서 요청 컨트롤러의 DTO 파라미터 앞에 @RequestBody 추가

문서 요청 관련 DTO 필드 수정 및 문서 위치 @Embedded로 변경

---

build.gradle
src/main/java/com/timcooki/jnuwiki/domain/docs/entity/DocsLocation.java
src/main/java/com/timcooki/jnuwiki/domain/docsRequest/entity/DocsCategory.java
src/test/java/com/timcooki/jnuwiki/docs/DocsRepositoryTest.java

- 검색 테스트
- build.gradle Test관련 mapstruct 설정 삭제

검색 테스트 코드 작성

---

src/main/java/com/timcooki/jnuwiki/domain/member/service/Validator.java

- 비밀번호 유효성 검증 정규식 변경 (대소문자 모두 포함에서 영어 포함으로)

비밀번호 유효성 검증 정규식 변경

---

src/main/java/com/timcooki/jnuwiki/domain/docs/entity/Docs.java
src/main/java/com/timcooki/jnuwiki/domain/docsArchive/entity/DocsArchive.java
src/main/java/com/timcooki/jnuwiki/domain/docsRequest/controller/DocsRequestController.java
src/main/java/com/timcooki/jnuwiki/domain/docsRequest/dto/request/EditWriteReqDTO.java
src/main/java/com/timcooki/jnuwiki/domain/docsRequest/entity/DocsRequest.java
src/main/java/com/timcooki/jnuwiki/domain/docsRequest/mapper/DocsRequestMapper.java
src/main/java/com/timcooki/jnuwiki/domain/docsRequest/service/DocsRequestService.java
src/main/java/com/timcooki/jnuwiki/domain/member/DTO/response/admin/EditReadResDTO.java
src/main/java/com/timcooki/jnuwiki/domain/member/DTO/response/admin/NewReadResDTO.java
src/main/java/com/timcooki/jnuwiki/domain/member/entity/Member.java
src/main/java/com/timcooki/jnuwiki/util/auditing/BaseTimeEntity.java

- mapper 클래스 member 매핑 에러 때문에 일부분 직접 구현하여 매핑함
- auditing 기능 
- 처음 생성 시간, 수정 시간, 생성한 사람에서 사용에서 생성 시간, 수정 시간에서만 사용, 생성한 사람은 직접 구현
- 엔티티, dto에서 auditing 사용으로 필요없는 부분들은 제거함

Auditing 기능 추가 Mapper 클래스 일부분 직접 구현

---

build.gradle
src/main/java/com/timcooki/jnuwiki/domain/docs/controller/DocsController.java
src/main/java/com/timcooki/jnuwiki/domain/docs/service/DocsService.java
src/main/java/com/timcooki/jnuwiki/domain/docsRequest/repository/DocsRequestRepository.java
src/main/java/com/timcooki/jnuwiki/domain/member/controller/AdminController.java
src/main/java/com/timcooki/jnuwiki/domain/member/service/AdminService.java
src/main/java/com/timcooki/jnuwiki/domain/member/service/MemberService.java
src/main/java/com/timcooki/jnuwiki/util/ApiResult.java
src/main/java/com/timcooki/jnuwiki/util/ApiUtils.java
src/main/java/com/timcooki/jnuwiki/util/errors/GlobalExceptionHandler.java
src/main/java/com/timcooki/jnuwiki/util/errors/exception/Exception400.java
src/main/java/com/timcooki/jnuwiki/util/errors/exception/Exception401.java
src/main/java/com/timcooki/jnuwiki/util/errors/exception/Exception403.java
src/main/java/com/timcooki/jnuwiki/util/errors/exception/Exception404.java
src/main/java/com/timcooki/jnuwiki/util/errors/exception/Exception500.java
src/test/java/com/timcooki/jnuwiki/docs/DocsRepositoryTest.java
src/test/java/com/timcooki/jnuwiki/domain/docsRequest/DocsRequestRepositoryTest.java

- 예외처리
- docs, docsRequest 레포 단위 테스트

예외처리 및 레포지토리 단위 테스트 일부분

---

src/main/java/com/timcooki/jnuwiki/domain/docs/service/DocsService.java
src/main/java/com/timcooki/jnuwiki/domain/docsRequest/service/DocsRequestService.java
src/main/java/com/timcooki/jnuwiki/domain/member/config/PostConstructorMember.java
src/main/java/com/timcooki/jnuwiki/domain/member/controller/AdminController.java
src/main/java/com/timcooki/jnuwiki/domain/member/service/AdminService.java
src/main/java/com/timcooki/jnuwiki/domain/security/config/AuthenticationConfig.java
src/main/java/com/timcooki/jnuwiki/util/JwtUtil/JwtUtil.java
src/test/java/com/timcooki/jnuwiki/domain/docsRequest/DocsRequestServiceTest.java

- 시큐리티 필터 관리자 검증 필터 버그 수정
- DocsRequestController 버그 수정
- DocsService 15일 체크 비활성화
- 서버 시작시 어드민 계정 생성
- 엑세스 토큰 300분으로 설정
- updateDocs 트랜잭션 설정(더티체킹이 안되는 이슈 해결)
- 15일 체크 테스트코드 작성
- 15일 체크 로직 localDate 에서 LocalDateTime 으로 수정
- 어드민 서비스 관리자 검증 로직 중복 삭제

여러 버그 수정 및 관리자 자동생성 추가

---

META-INF/MANIFEST.MF
build.gradle
src/main/java/com/timcooki/jnuwiki/domain/docs/DTO/response/ListReadResDTO.java
src/main/java/com/timcooki/jnuwiki/domain/docs/DTO/response/ReadResDTO.java
src/main/java/com/timcooki/jnuwiki/domain/docs/DTO/response/SearchReadResDTO.java
src/main/java/com/timcooki/jnuwiki/domain/docs/controller/DocsController.java
src/main/java/com/timcooki/jnuwiki/domain/docs/entity/Docs.java
src/main/java/com/timcooki/jnuwiki/domain/docs/mapper/DocsMapper.java
src/main/java/com/timcooki/jnuwiki/domain/docs/service/DocsService.java
src/main/java/com/timcooki/jnuwiki/domain/docsArchive/entity/DocsArchive.java
src/main/java/com/timcooki/jnuwiki/domain/docsRequest/controller/DocsRequestController.java
src/main/java/com/timcooki/jnuwiki/domain/docsRequest/entity/DocsRequest.java
src/main/java/com/timcooki/jnuwiki/domain/docsRequest/service/DocsRequestService.java
src/main/java/com/timcooki/jnuwiki/domain/member/config/PostConstructorMember.java
src/main/java/com/timcooki/jnuwiki/domain/member/controller/AdminController.java
src/main/java/com/timcooki/jnuwiki/domain/member/controller/MemberController.java
src/main/java/com/timcooki/jnuwiki/domain/member/service/AdminService.java
src/main/java/com/timcooki/jnuwiki/domain/member/service/MemberService.java
src/main/java/com/timcooki/jnuwiki/domain/security/config/CorsConfig.java
src/main/java/com/timcooki/jnuwiki/domain/security/service/MemberSecurityService.java
src/main/java/com/timcooki/jnuwiki/domain/security/service/RefreshTokenService.java
src/test/java/com/timcooki/jnuwiki/docs/DocsRepositoryTest.java
src/test/java/com/timcooki/jnuwiki/domain/docsRequest/DocsRequestRepositoryTest.java
src/test/java/com/timcooki/jnuwiki/domain/docsRequest/DocsRequestServiceTest.java

- 예외 처리
- 엔티티 노출 삭제
- CORS에러 설정 파일 생성
- 빌드 오류로 인한 테스트코드 한글제목 삭제
- DocsMapper 수정
- 모델 strategy 속성 추가

예외처리 & 버그 수정

---

src/main/java/com/timcooki/jnuwiki/domain/security/config/CorsConfig.java

CORS 설정 추가

---

build.gradle
src/main/java/com/timcooki/jnuwiki/domain/docs/DTO/response/ListReadResDTO.java
src/main/java/com/timcooki/jnuwiki/domain/docs/controller/DocsController.java
src/main/java/com/timcooki/jnuwiki/domain/docs/service/DocsService.java
src/main/java/com/timcooki/jnuwiki/domain/docsRequest/entity/DocsCategory.java
src/main/java/com/timcooki/jnuwiki/domain/member/config/PostConstructorMember.java
src/main/java/com/timcooki/jnuwiki/domain/member/service/AdminService.java
src/main/java/com/timcooki/jnuwiki/domain/security/config/AuthenticationConfig.java

- 회원가입 시 이메일, 닉네임 중복 체크 경로 접근 시 접근 권한 적용 되어 접근 가능하게 수정
- '--enable-preview'이 자바 21부터 사용 가능하다고 빌드 에러떠서 지움
- 프론트 마커 에러로 인해 문서 위치의 임시 데이터를 전남대 위치로 변경
- 임시 데이터 수정 반영 @PostConstruct

접근 권한 적용 및 기타 에러 해결

---

src/main/java/com/timcooki/jnuwiki/domain/docsRequest/service/DocsRequestService.java

- 수정 요청이 없을 경우 응답을 빈 응답 코드에서 404에러로 변경

요청이 없을 경우 응답 변경

---

build.gradle
src/main/java/com/timcooki/jnuwiki/configuration/SwaggerConfig.java
src/main/java/com/timcooki/jnuwiki/domain/security/config/AuthenticationConfig.java

- Sweager 의존성 추가
- Config 파일 작성
- Authentication Filter 설정 추가

Sweager 적용

---

src/main/java/com/timcooki/jnuwiki/domain/member/config/PostConstructorMember.java
src/main/java/com/timcooki/jnuwiki/domain/security/config/AuthenticationConfig.java
src/test/java/com/timcooki/jnuwiki/docs/DocsControllerTest.java

- 문서조회 권한 전체 가능하게 수정
- 문서 조회 권한 테스트코드 작성
- 더미데이터 DocsCategory부분 삭제 및 수정

문서조회 권한 수정

---

src/main/java/com/timcooki/jnuwiki/domain/member/service/MemberService.java
src/main/java/com/timcooki/jnuwiki/domain/scrap/DTO/request/DeleteScrapReqDTO.java
src/main/java/com/timcooki/jnuwiki/domain/scrap/DTO/request/NewScrapReqDTO.java
src/main/java/com/timcooki/jnuwiki/domain/scrap/controller/ScrapController.java
src/main/java/com/timcooki/jnuwiki/domain/scrap/repository/ScrapRepository.java
src/main/java/com/timcooki/jnuwiki/domain/scrap/service/ScrapService.java
src/test/java/com/timcooki/jnuwiki/scrap/controller/ScrapControllerTest.java
src/test/java/com/timcooki/jnuwiki/scrap/service/ScrapServiceTest.java

- 사용자가 비밀번호 업데이트시 암호화하는 로직 추가
- 스크랩 생성 컨트롤러&서비스&레포지토리
- 스크랩 삭제 컨트롤러&서비스&레포지토리
- 스크랩 생성 및 삭제 서비스 단위테스트
- 스크랩 생성 및 삭제 컨트롤러 단위테스트

스크랩 생성 및 삭제 구현, 사용자가 비밀번호 업데이트시 암호화 안되는 버그 픽스

---

src/test/java/com/timcooki/jnuwiki/scrap/repository/ScrapRepositoryTest.java

- 스크랩 생성 save 메서드 단위테스트
- 스크랩 삭제 deleteById 메서드 단위테스트
- 작업 사항
closes #48

feat: Scrap 생성, 삭제 Respository 단위테스트

---

src/main/java/com/timcooki/jnuwiki/domain/docs/DTO/request/FindAllReqDTO.java
src/main/java/com/timcooki/jnuwiki/domain/docs/controller/DocsController.java
src/main/java/com/timcooki/jnuwiki/domain/docs/repository/DocsRepository.java
src/main/java/com/timcooki/jnuwiki/domain/docs/service/DocsService.java
src/main/java/com/timcooki/jnuwiki/domain/docsRequest/entity/DocsCategory.java
src/test/java/com/timcooki/jnuwiki/docs/DocsControllerTest.java
src/test/java/com/timcooki/jnuwiki/domain/docs/DocsRepositoryTest.java

- 문서조회 구현
- 문서조회권한 테스트 수정
- 음식점 카테고리 추가
- 문서조회 레포지토리 테스트
closes #54

Feat cookie

---

src/test/java/com/timcooki/jnuwiki/docs/DocsControllerTest.java
src/test/java/com/timcooki/jnuwiki/domain/docs/DocsReadServiceTest.java
src/test/java/com/timcooki/jnuwiki/domain/docsRequest/DocsRequestReadServiceTest.java

- 빌드를 위한 수정되지 않은 테스트 코드 주석 처리
- 추후 리팩토링을 위한 TODO 주석 추가
- 빌드를 위한 수정되지 않은 테스트코드 주석 처리
- 테스트코드 리팩토링 위한 TODO 주석 추가

빌드를 위한 수정되지 않은 테스트코드 주석 처리

---

src/main/java/com/timcooki/jnuwiki/domain/docsRequest/service/DocsRequestWriteService.java

테스트용 문서 생성, 수정 권한 일부 삭제

---

src/main/java/com/timcooki/jnuwiki/domain/member/DTO/response/LoginResDTO.java
src/main/java/com/timcooki/jnuwiki/domain/member/service/MemberWriteService.java
src/main/java/com/timcooki/jnuwiki/util/JwtUtil/JwtUtil.java

- 로그인시 토큰 만료 시간 추가
- API 문서 업데이트

로그인시 응답에 토큰 만료 시간 추가

---

build.gradle
src/main/java/com/timcooki/jnuwiki/domain/member/DTO/request/JoinReqDTO.java
src/main/java/com/timcooki/jnuwiki/domain/member/controller/MemberController.java
src/main/java/com/timcooki/jnuwiki/domain/member/valid/Nickname.java
src/main/java/com/timcooki/jnuwiki/domain/member/valid/NicknameValidator.java
src/main/java/com/timcooki/jnuwiki/util/errors/GlobalExceptionHandler.java
src/test/java/com/timcooki/jnuwiki/domain/member/validation/NicknameValidatorTest.java

- 닉네임 자리수 8글자 제한
- 테스트코드
closes #143

닉네임 자리수 8글자 제한
